/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package refresher.basics;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static int method1()
    {
        try {
            int a = 22/0;
            return 1;
        } catch (Exception e) {
            return 2;
        }finally{
            return 3;
        }

        // return 4;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Canine canine = new Dog();
        try {
            canine.hello();
        } catch (Exception e) {
            System.out.println("Exception Handled!");
        }

        int result = method1();
        System.out.println(result);

        demoStringBufferAndBuilder();

        comparableDemo();
    }

    static void demoStringBufferAndBuilder() {
        
        StringBuilder sb1 = new StringBuilder("hello");
        StringBuilder sb2 = new StringBuilder("hello");

        if(sb1.equals(sb2)){
            System.out.println("sb1 equals sb2");
        }else{
            System.out.println("sb1 not equal sb2!");
        }
    }

    static void comparableDemo(){
        List<Employee> empList = new ArrayList<>();
        empList.add(new Employee(4, "Dave", 25, 28000));
        empList.add(new Employee(20, "Mike", 25, 10000));
        empList.add(new Employee(9, "Abhi", 25, 5000));
        empList.add(new Employee(1, "Lisa", 25, 19000));

        Collections.sort(empList);
        System.out.println(empList);
    }
}
